blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/FanWuu/viper/discussions/new?category=q-a
    about:  Ask and discuss questions with other Viper community members

  - name: 📓 Reference
    url: https://pkg.go.dev/mod/github.com/FanWuu/viper
    about: Check the Go code reference

  - name: 💬 Slack channel
    url: https://gophers.slack.com/messages/viper
    about: Please ask and answer questions here
